name: Publish Docker image

on:
    workflow_dispatch:
        inputs:
            mumble_version:
                description: "The version (tag or commit hash) of Mumble to build"
                required: true
                default: "latest"
            docker_version:
                description: "Docker image version, independent of mumble version"
                required: true
                default: "0"
            publish:
                description: "Whether the built image(s) shall be published to Dockerhub"
                required: true
                default: "false"

jobs:
    docker:
        uses: mumble-voip/mumble-docker/.github/workflows/build_and_publish.yml@master
        with:
            mumble_version: ${{ inputs.mumble_version }}
            docker_version: ${{ inputs.docker_version }}
            publish: ${{ inputs.publish == "true" }}
            platforms: "linux/amd64"
